version: 1
disable_existing_loggers: true

formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: /tmp/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: ascii

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /tmp/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: ascii

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /tmp/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: ascii

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: /tmp/critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: ascii

    warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: standard
        filename: /tmp/warn.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: ascii


root:
    level: NOTSET
    handlers: [console]
    propogate: yes

loggers:
    sampleLogger:
        level: DEBUG
        handlers: [console]
        propagate: no

    workers:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler, debug_file_handler, critical_file_handler, warn_file_handler]
        propagate: yes

    app:
        level: INFO
        handlers: [info_file_handler, error_file_handler, debug_file_handler, critical_file_handler, warn_file_handler]
        propagate: no

    app.auth:
        level: INFO
        handlers: [info_file_handler, error_file_handler, debug_file_handler, critical_file_handler, warn_file_handler]
        propagate: no

    app.dummy_feature:
        level: INFO
        handlers: [info_file_handler, error_file_handler, debug_file_handler, critical_file_handler, warn_file_handler]
        propagate: no

    app.errors:
        level: ERROR
        handlers: [info_file_handler, error_file_handler, debug_file_handler, critical_file_handler, warn_file_handler]
        propagate: no

    app.features:
        level: INFO
        handlers: [info_file_handler, error_file_handler, debug_file_handler, critical_file_handler, warn_file_handler]
        propagate: no

    app.management:
        level: INFO
        handlers: [info_file_handler, error_file_handler, debug_file_handler, critical_file_handler, warn_file_handler]
        propagate: no
