"""sensorRoom table

Revision ID: 073ec00c8afe
Revises: 7250354c81cb
Create Date: 2020-05-15 16:08:44.301646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073ec00c8afe'
down_revision = '7250354c81cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SensorRoom',
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('sensor_id', 'room_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SensorRoom')
    # ### end Alembic commands ###
