"""sensor table

Revision ID: 36efa084da0c
Revises: d64b5df8113b
Create Date: 2020-05-15 15:05:06.341926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36efa084da0c'
down_revision = 'd64b5df8113b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor')
    # ### end Alembic commands ###
