"""sensor table

Revision ID: 810eb195a357
Revises: 3412d72e480d
Create Date: 2020-05-15 15:31:03.439696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810eb195a357'
down_revision = '3412d72e480d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor')
    # ### end Alembic commands ###
